### ISSUE TITLE
zooql not showing

### ISSUE THREAD

**Issue by grolongo** [444995/qbit-search-plugins#1]
Hi, I'm trying to use your plugin in qbittorrent but for some reason it doesn't show up in the list of installed plugins. I have it installed alongside other plugins in the correct folder, not sure why yours isn't listed in qbittorrent.

**Comment by 444995** [comment]
Hey! Sorry for responding so late.

I just tried installing it again and it worked for me. What operating system are you on? 

And I hate to be that guy but are you sure you picked the right file when installing and you scrolled all the way down when checking if it's installed?

Also, did it give you any errors when installing it?

**Comment by grolongo** [comment]
>Hey! Sorry for responding so late.

no issue :)

>I just tried installing it again and it worked for me. What operating system are you on?

so I tried again as well, it's still not working on Windows 11 nor macOS, but it is working on Linux (Ubuntu).

>And I hate to be that guy but are you sure you picked the right file when installing and you scrolled all the way down when checking if it's installed?

no problem and yes I confirm I used the right file and I double checked the bottom of the list.

>Also, did it give you any errors when installing it?

so I have no error on Ubuntu as it's working just fine, but on Windows and macOS it simply says:
`Couldn't update "zooqle" search engine plugin. Plugin is not supported.`
right after I try to import it.

**Comment by 444995** [comment]
I've tried to recreate the issue on both Mac and Windows, and I just can't. It succesfully installs for me.
Can you try to enable logging by going to 'View' -> 'Log' to enable all the different verbosity levels and click "Show" to show the log tab, and then try to install it again?

Tell me what it says.

**Comment by grolongo** [comment]
So I activated the logs with all verbosity (normal, information, warning, critical messages). It only prints the error message from the dialog box `Plugin zooqle isn't supported."`, nothing else that can help us :/  

When you are on Windows are you testing on 4.6.6? To make sure this is how I can reproduce this issue:

**1st way**:

From a PowerShell prompt:

`Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/444995/qbit-search-plugins/main/engines/zooqle.py' -OutFile "$HOME\AppData\Local\qBittorrent\nova3\engines\zooqle.py"`

Open qBittorrent => Search => Search plugins... => zooqle isn't showing.

**2nd way**:

`Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/444995/qbit-search-plugins/main/engines/zooqle.py' -OutFile "$HOME\Desktop\zooqle.py"`

Open qBittorrent => Search => Search plugins... =>Install a new one =>Local file => choose zooqle.py in Desktop folder
then the error dialog gets printed.

**Comment by 444995** [comment]
Try now and let me know if it works.

**Comment by grolongo** [comment]
Everything works as expected. Thanks a lot for the help. 👍
