### ISSUE TITLE
Unsupported plugin

### ISSUE THREAD

**Issue by ElimGarak72** [444995/qbit-search-plugins#2]
Hello!
I cannot install this plugin.
It keeps saying that it is unsupported. I have tried using the link and downloading it, with no success.
My qbitorrent version is 4.6.6 and Python is 3.12 64 bit, so everything shoud be fine.

Thank you.

**Comment by 444995** [comment]
What specific plugin are you referring to? I have multiple :D

And what operating system are you on?

**Comment by samugarciax** [comment]
hi, same issue with torrentleech. latest python currently installed, macos latest,  qbit is 4.6.0

**Comment by ElimGarak72** [comment]
> What specific plugin are you referring to? I have multiple :D
> 
> And what operating system are you on?

Hello!
The plugin is for Zooqle.
My OS is Windows 10 Pro 64 bit.
Thank you

**Comment by 444995** [comment]
Another guy had the same error. I've pushed an update so it should work now. Go ahead and close this if it also works for you.

**Comment by 444995** [comment]
> hi, same issue with torrentleech. latest python currently installed, macos latest, qbit is 4.6.0

I've tested it on macOs and it works for me. You have to fill in username and password also before using it.

**Comment by ElimGarak72** [comment]
Zooqle plugin seems to work now, thank you.

**Comment by 444995** [comment]
@samugarciax Update? :D

@ElimGarak72 Perfect!

**Comment by Saloframes** [comment]
Having the same issue with the Torrentleech plugin.

**Comment by 444995** [comment]
> Having the same issue with the Torrentleech plugin.

Can you try to fill the credentials in and then just run the torrentleech file with python normally, and tell me what it says?

**Comment by Saloframes** [comment]
Got it working! No idea what I did, re-downloaded it and used my credentials.
